### ISSUE TITLE
maybe EEPROM overwrite issue?

### ISSUE THREAD

**Issue by chrwei** [CuriousTech/ESP8266-HVAC#7]
I haven't noticed any effects of this, but you have `WiFiManager wifi(0);` which the 0 means to start EEPROM at zero, then in the WiFiManager class a new SSID and PW is written to the first 64 bytes of EEPROM using setEEPROMString().  but then the eeWrite function puts hvac.m_EE to eeWriteData which also write the first 64 bytes of EEPROM, overwriting the saved SSID and PW.

and I reading something wrong here?

**Comment by CuriousTech** [comment]
Update the source.  I merged it all in eeMem.cpp/h a while back and just have it as a global struct.  That way WiFiManager can just update the SSID/pass fields instead of wiping out the rest if it writes.

**Comment by CuriousTech** [comment]
@chrwei I just updated a lot of code (sorry).  I forgot that I was going to change the WiFiManager to use the AsyncWebServer class so I could remove all the synchronous code.  It freed up a good chunk of space, but it's at 192.168.4.1:85 because I'm using the main instance on port 85. Another instance would fix that but would use more space.  It doesn't need to reboot and maybe get stuck now, though.
